baseURL = "https://wangrunlin.github.io/blog/"
# title = "Hugo Themes"
author = "Leo Wang"
copyright = "Copyright © 2022 Leo Wang; all rights reserved."
paginate = 5
languageCode = "zh"
DefaultContentLanguage = "zh"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# ------------------------------
theme = "paper"
title = "Leo Wang"

[params]
  # color = 'linen'

  twitter = 'wangrunlin_'
  github = 'wangrunlin'
  # instagram = 'nan.xiaobei'

  avatar = 'https://github.com/wangrunlin.png'
  name = '阿林'
  bio = '🌟 Web Developer & Lifelong learner'

  # https://umami.is Umami is an open source, privacy-focused alternative to Google Analytics
  [params.umami]
    enable = true
    code = '<script async defer data-website-id="fa906209-3da5-4ec4-937c-7c5468eca37f" src="https://stats.wangrunlin.com/umami.js"></script>'

# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
    [[menu.main]]
      identifier = "about"
      name = "About"
      url = "https://wangrunlin.com"
      weight = 10
  # [[menu.main]]
  #   identifier = "contact"
  #   name = "Contact"
  #   url = "/contact/"
  #   weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
